### ISSUE TITLE
Protocol usage

### ISSUE THREAD

**Issue by lfarah** [aschuch/StatefulViewController#26]
As [Ray Wenderlich discusses here](https://github.com/raywenderlich/swift-style-guide#protocol-conformance), ```when adding protocol conformance to a model, prefer adding a separate extension for the protocol methods. ```.

So this:
``` swift
class MyViewController: UIViewController, StatefulViewController {
    // ...
}
```

should be like this:
``` swift
extension MyViewController: StatefulViewController {

func loadDeliciousWines() {
    startLoading()

    let url = NSURL(string: "http://example.com/api")
    let session = NSURLSession.sharedSession()
    session.dataTaskWithURL(url) { (let data, let response, let error) in
        endLoading(error: error)
    }.resume()
                                          }
}

**Comment by aschuch** [comment]
Ray Wenderlich _proposes_ a guideline rather than a _definite way_ to write code.
That said, the guideline actually proposes to add all methods within the `StatefulViewController` protocol to an extension, in order to increase readability.

For example, the `hasContent` method might be extracted into an extension on `MyViewController`, but `loadDeliciousWines` would still stay part of the main ViewController definition.

Does that answer your question?

**Comment by lfarah** [comment]
Sure, definitely 😄
