### ISSUE TITLE
Use with UITableViewController or UICollectionViewController?

### ISSUE THREAD

**Issue by markkrenek** [aschuch/StatefulViewController#3]
Is there any suggestion for using this with a UITableViewController or UICollectionViewController?

**Comment by markkrenek** [comment]
I just tried an experiment where I made StatefulViewController an extension of UIViewController instead of a subclass meaning that it provides its functionality to any UIViewController (whether you want or not). It seems to work fine with these caveats:

- viewWillAppear can't be overridden by an extension so instead, view controller implementations need to call the replacement method statefulViewWillAppear().

- As an extension, all UIViewControllers now inherit the computed properties defined by StatefulViewController (currentState, lastState, loadingView, etc.).

- In order to store properties (which aren't supported by extensions), I use objc_setAssociatedObject.

I'm not a big expert on Swift yet, so I can't say if this is a viable solution. It seems a bit kludgy. The other thought is that StatefulViewController could be a protocol.

**Comment by aschuch** [comment]
This sounds very promising indeed. Do you mind sharing your code or even open a WIP pull request?

**Comment by markkrenek** [comment]
See PR https://github.com/aschuch/StatefulViewController/pull/8

**Comment by aschuch** [comment]
Hi @markkrenek, based on the changes of protocol extensions in Swift 2.0, I decided to turn StatefulViewController into a protocol instead of directly providing a UIViewController extension. 
This gives us the flexibility of an extension, but not every UIViewController inherits properties that may never be used.

Would love to get your feedback on my PR #10.
:heart:
