### ISSUE TITLE
currentState not updated after startLoading being called

### ISSUE THREAD

**Issue by mschonvogel** [aschuch/StatefulViewController#5]
The _loadInitialData_ method is called multiple times (viewDidLoad, UIApplicationDidBecomeActive) and is always doing the Network request. After calling startLoading() the currentState var will not be updated. The printed loadingState is always _content_. 
```swift
    func loadInitialData()
    {
        println(currentState.rawValue)
        if (currentState == .Loading) {
            return
        }
        startLoading()
        println("loadingState: \(currentState.rawValue)")
        FoyerApi.shared.getStories(refresh:true, lastStoryId: nil) { (stories:[Story]?, error:NSError?) in
            self.endLoading(error: error)
            if let _stories = stories {
                self.insertStories(_stories, refresh: true)
            }
        }
    }
```

**Comment by aschuch** [comment]
Thanks for reporting. This is due to the async nature of the state machine. So calling `currentState` immediately after a call to `startLoading` does not yield the updated value (yet).

I think the only way to provide you with the current state is via a completion block on the `startLoading` and `endLoading` calls. 

Would that be sufficient for you?

**Comment by aschuch** [comment]
Hi @mschonvogel, please check out the new `lastState` property, which refers to the last enqueued state. Also note the completion blocks on start and endLoading.

**Comment by mschonvogel** [comment]
Thank you and sorry for missing your post! This fixes the problem for me.
